.TH "src Directory Reference" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBandroid\fP"
.br
.ti -1c
.RI "directory \fBaudiofilters\fP"
.br
.ti -1c
.RI "directory \fBbase\fP"
.br
.ti -1c
.RI "directory \fBotherfilters\fP"
.br
.ti -1c
.RI "directory \fBupnp\fP"
.br
.ti -1c
.RI "directory \fBvideofilters\fP"
.br
.ti -1c
.RI "directory \fBvoip\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbasedescs\&.h\fP"
.br
.ti -1c
.RI "file \fBdxfilter\&.h\fP"
.br
.ti -1c
.RI "file \fBfilter-template\&.c\fP"
.br
.ti -1c
.RI "file \fBgitversion\&.h\fP"
.br
.ti -1c
.RI "file \fBvoipdescs\&.h\fP"
.br
.ti -1c
.RI "file \fByuv2rgb\&.fs\&.h\fP"
.br
.ti -1c
.RI "file \fByuv2rgb\&.vs\&.h\fP"
.br
.in -1c
