.TH "videofilters Directory Reference" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
videofilters Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdrawdib-display\&.c\fP"
.br
.ti -1c
.RI "file \fBextdisplay\&.c\fP"
.br
.ti -1c
.RI "file \fBglxvideo\&.c\fP"
.br
.ti -1c
.RI "file \fBh264dec\&.c\fP"
.br
.ti -1c
.RI "file \fBjpegwriter\&.c\fP"
.br
.ti -1c
.RI "file \fBmire\&.c\fP"
.br
.ti -1c
.RI "file \fBmsv4l\&.c\fP"
.br
.ti -1c
.RI "file \fBmsv4l2\&.c\fP"
.br
.ti -1c
.RI "file \fBnowebcam\&.c\fP"
.br
.ti -1c
.RI "file \fBpixconv\&.c\fP"
.br
.ti -1c
.RI "file \fBsizeconv\&.c\fP"
.br
.ti -1c
.RI "file \fBtheora\&.c\fP"
.br
.ti -1c
.RI "file \fBvideodec\&.c\fP"
.br
.ti -1c
.RI "file \fBvideoenc\&.c\fP"
.br
.ti -1c
.RI "file \fBvideoout\&.c\fP"
.br
.ti -1c
.RI "file \fBvp8\&.c\fP"
.br
.ti -1c
.RI "file \fBwincevideods\&.c\fP"
.br
.ti -1c
.RI "file \fBwinvideo\&.c\fP"
.br
.ti -1c
.RI "file \fBwinvideo2\&.c\fP"
.br
.ti -1c
.RI "file \fBwinvideods\&.c\fP"
.br
.ti -1c
.RI "file \fBx11video\&.c\fP"
.br
.in -1c
