.TH "base Directory Reference" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBeventqueue\&.c\fP"
.br
.ti -1c
.RI "file \fBmscommon\&.c\fP"
.br
.ti -1c
.RI "file \fBmsfilter\&.c\fP"
.br
.ti -1c
.RI "file \fBmsqueue\&.c\fP"
.br
.ti -1c
.RI "file \fBmssndcard\&.c\fP"
.br
.ti -1c
.RI "file \fBmsticker\&.c\fP"
.br
.ti -1c
.RI "file \fBmswebcam\&.c\fP"
.br
.ti -1c
.RI "file \fBmtu\&.c\fP"
.br
.in -1c
