.TH "_IceTransportAddress" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IceTransportAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ice\&.h>\fP
.SH "Detailed Description"
.PP 
Structure representing an ICE transport address\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
