.TH "_IceSession" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IceSession \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ice\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "MSList * \fBstreams\fP"
.br
.ti -1c
.RI "char * \fBlocal_ufrag\fP"
.br
.ti -1c
.RI "char * \fBlocal_pwd\fP"
.br
.ti -1c
.RI "char * \fBremote_ufrag\fP"
.br
.ti -1c
.RI "char * \fBremote_pwd\fP"
.br
.ti -1c
.RI "\fBIceRole\fP \fBrole\fP"
.br
.ti -1c
.RI "\fBIceSessionState\fP \fBstate\fP"
.br
.ti -1c
.RI "uint64_t \fBtie_breaker\fP"
.br
.ti -1c
.RI "uint32_t \fBta\fP"
.br
.ti -1c
.RI "uint8_t \fBmax_connectivity_checks\fP"
.br
.ti -1c
.RI "uint8_t \fBkeepalive_timeout\fP"
.br
.ti -1c
.RI "MSTimeSpec \fBevent_time\fP"
.br
.ti -1c
.RI "bool_t \fBsend_event\fP"
.br
.ti -1c
.RI "struct sockaddr_storage \fBss\fP"
.br
.ti -1c
.RI "socklen_t \fBss_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing an ICE session\&. 
.SH "Field Documentation"
.PP 
.SS "MSList* _IceSession::streams"
List of IceChecklist structures\&. Each element of the list represents a media stream 
.SS "char* _IceSession::local_ufrag"
Local username fragment for the session (assigned during the session creation) 
.SS "char* _IceSession::local_pwd"
Local password for the session (assigned during the session creation) 
.SS "char* _IceSession::remote_ufrag"
Remote username fragment for the session (provided via SDP by the peer) 
.SS "char* _IceSession::remote_pwd"
Remote password for the session (provided via SDP by the peer) 
.SS "\fBIceRole\fP _IceSession::role"
Role played by the agent for this session 
.SS "\fBIceSessionState\fP _IceSession::state"
State of the session 
.SS "uint64_t _IceSession::tie_breaker"
Random number used to resolve role conflicts (see paragraph 5\&.2 of the RFC 5245) 
.SS "uint32_t _IceSession::ta"
Duration of timer for sending connectivity checks in ms 
.SS "uint8_t _IceSession::max_connectivity_checks"
Configuration parameter to limit the number of connectivity checks performed by the agent (default is 100) 
.SS "uint8_t _IceSession::keepalive_timeout"
Configuration parameter to define the timeout between each keepalive packets (default is 15s) 
.SS "MSTimeSpec _IceSession::event_time"
Time when an event must be sent 
.SS "bool_t _IceSession::send_event"
Value of the event to send Boolean value telling whether an event must be sent or not 
.SS "struct sockaddr_storage _IceSession::ss"
STUN server address to use for the candidates gathering process 
.SS "socklen_t _IceSession::ss_len"
Length of the STUN server address to use for the candidates gathering process 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
