.TH "_MSAudioConferenceParams" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MSAudioConferenceParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msconference\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsamplerate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that holds audio conference parameters 
.SH "Field Documentation"
.PP 
.SS "int _MSAudioConferenceParams::samplerate"
Conference audio sampling rate in Hz: 8000, 16000 \&.\&.\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
