.TH "_MSQSAWriteData" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MSQSAWriteData \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition of the private data structure of the QSA playback filter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
