.TH "_MSToneDetectorEvent" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MSToneDetectorEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mstonedetector\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBtone_start_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure carried as argument of the MS_TONE_DETECTOR_EVENT 
.SH "Field Documentation"
.PP 
.SS "uint64_t _MSToneDetectorEvent::tone_start_time"
Tone start time in millisecond 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
