.TH "Audio filters" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio filters \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fB- SILK (Skype codec)  plugin\fP"
.br
.RI "\fISILK Speech Codec (draft-vos-silk-02) plugins filters to encode and decode audio\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
