.TH "Mediastreamer2's base APIs" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mediastreamer2's base APIs \- 
.PP
Base APIs of mediastreamer2\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBStarting mediastreamer2 library\fP"
.br
.RI "\fIStarting mediastreamer2 library\&. \fP"
.ti -1c
.RI "\fBSound Card API - Manage audio capture/play filters\fP"
.br
.RI "\fISound Card API to manage audio capture/play filters\&. \fP"
.ti -1c
.RI "\fBFilter API - Manage mediastreamer2 filters\fP"
.br
.RI "\fIFilter API to manage mediastreamer2 filters\&. \fP"
.ti -1c
.RI "\fBTicker API - Manage mediastreamer2 graphs\fP"
.br
.RI "\fITicker API to manage mediastreamer2 graphs\&. \fP"
.ti -1c
.RI "\fBCamera API - manage video capture devices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base APIs of mediastreamer2\&. 

Mediastreamer2 expose a low level API to directly control filters, chain and have them running\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
