.TH "Mediastreamer2's high level APIs" 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mediastreamer2's high level APIs \- 
.PP
High level APIs of mediastreamer2\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAudio streaming API - Create and run VoIP audio streams\&.\fP"
.br
.RI "\fIAudio streaming API - Easily run audio streams from soundcard or wav files to RTP\&. \fP"
.ti -1c
.RI "\fBAudio conferencing API - Easily create conferences\&.\fP"
.br
.RI "\fIAudio conferencing API - Easily create conferences\&. \fP"
.ti -1c
.RI "\fBVideo streaming API - Create and run video streams\&.\fP"
.br
.RI "\fIVideo streaming API - Easily run video streams from camera capture or static picture files to RTP\&. \fP"
.ti -1c
.RI "\fBRing playing API - Play ring files\&.\fP"
.br
.RI "\fIRing playing API - Easily play a local ring from a wav file\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
High level APIs of mediastreamer2\&. 

The high level apis are designed to provide an easy way to create audio or video processing graphs for VoIP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
