.TH "Ring playing API - Play ring files." 3 "Tue May 13 2014" "Version 2.10.0" "mediastreamer2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ring playing API - Play ring files. \- 
.PP
Ring playing API - Easily play a local ring from a wav file\&.  

.SH "Detailed Description"
.PP 
Ring playing API - Easily play a local ring from a wav file\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mediastreamer2 from the source code\&.
